runtime: nodejs20
service: tugas6-179-fe
instance_class: F1

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

default_expiration: "1h"