GET http://localhost:5000/users


###
GET http://localhost:5000/catatan/7

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "hari",
    "email": "hari@suke",
    "gender": "L",
    "password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "hari@suke",
    "password": "123456"
}

###
PUT http://localhost:5000/edit-catatan/7
Content-Type: application/json

{
    "Judul": "resep obat",
    "Isi": "campur obat ini dengan air hangat",
    "Tanggal": "21-09-2022"
}

###
DELETE http://localhost:5000/delete-catatan/8